### ISSUE TITLE
Various issues with 2.2018 versions

### ISSUE THREAD

**Issue by Deimos** [nexB/python-publicsuffix2#1]
There have been two recent updates to this package on pypi which are quite strange in various ways:

* The package can no longer be imported as `publicsuffix` like the docs show, it must now be `publicsuffix2` (so the example code in the docs no longer works)
* The changelog on pypi hasn't been updated for the most recent 2 releases, and this repo also hasn't been updated in years
* The newest version (2.20180921.2) no longer seems to download the publicsuffix file, it just uses the one included?

Are you still the maintainer of this package? What's happening with it?

**Comment by Deimos** [comment]
@pombredanne

**Comment by pombredanne** [comment]
@Deimos sorry for missing that ticket earlier..! let me review and fix this alright

**Comment by pombredanne** [comment]
> Are you still the maintainer of this package?  

yes
 
>What's happening with it?

the bundled data list is updated now and then and a new release pushed.

Sorry for forgetting to update the CHANGELOG and README! this has been corrected now. And I pushed a new version with the latest PSL data file.


> The newest version (2.20180921.2) no longer seems to download the publicsuffix file, it just uses the one included?

Yes, and there is a setup command to fetch the latest. I could reinstate the fetch() function easily though

**Comment by Deimos** [comment]
Thank you. I was mostly just confused about the changes happening silently, appreciate you updating everything.

**Comment by pombredanne** [comment]
@Deimos I usually do this the proper way: I had no idea anyone was using this smaller lib here :)

**Comment by reneeburton** [comment]
I am also using it. I have to adjust calls to handle idna-encoded domains, but otherwise it's much faster than publicsuffixlist. thank you. 

I'd like to see the fetch() method back in, as I install the module on EMR clusters and don't run the setup. the fetch() allowed me to pull a recent version and shove it to all the nodes. 

in any case, thank you for creating and maintaining this library.

**Comment by pombredanne** [comment]
@Deimos @reneeburton let me add this fetch() back. That's an easy one. and sorry for having pulled that out without warning.
This is done and released (with a data and doc update at Pypi as v2.20190205  https://pypi.org/project/publicsuffix2/

**Comment by pombredanne** [comment]
@Deimos FYI I should have pinged you here back then, but I had addressed your comments in the release https://pypi.org/project/publicsuffix2/2.20181213/

**Comment by Deimos** [comment]
Thanks @pombredanne, appreciate the updates (and the ping)!
