### ISSUE TITLE
Dashes cause parsing error

### ISSUE THREAD

**Issue by keithjjones** [nexB/python-publicsuffix2#15]
Try these examples, this looks like a bug to me.  Note that all I did was remove the dash from "compute-1".  I would expect the tld to be "compute-1.amazonaws.com" and the sld to be "amazonaws.com".  

```
>>> get_tld('ec2-107-21-74-29.compute-1.amazonaws.com')
'ec2-107-21-74-29.compute-1.amazonaws.com'
>>> get_sld('ec2-107-21-74-29.compute-1.amazonaws.com')
'ec2-107-21-74-29.compute-1.amazonaws.com'
>>> get_sld('ec2-107-21-74-29.compute1.amazonaws.com')
'compute1.amazonaws.com'
>>> get_tld('ec2-107-21-74-29.compute1.amazonaws.com')
'amazonaws.com'
```

**Comment by keithjjones** [comment]
My bad, I guess they do specify it:

https://github.com/publicsuffix/list/blob/master/public_suffix_list.dat#L10694

Closing.

**Comment by pombredanne** [comment]
@keithjjones not your bad: the suffix list moves in a mysterious way and things are often not what they look like!
