### ISSUE TITLE
code upgrade

### ISSUE THREAD

**Issue by KnitCode** [nexB/python-publicsuffix2#3]
hi, i submitted a PR in March to fix issues related to the now-UTF8 encoding of the PSL and add some functionality. There were some bugs in that which eluded my test checks. Those are now fixed. I am unable to request a review in the PR. My preference is to have the changes merged into publicsuffix2, so we don't have to change our various code bases to a new module name. appreciate a review and either accept, or reject and we'll set up a new module in pypi. thanks!

**Comment by pombredanne** [comment]
#2 has been merged. @KnitCode Thanks!

**Comment by pombredanne** [comment]
@KnitCode I also updated to the latest PSL and pushed a release to Pypi https://pypi.org/project/publicsuffix2/ ... Thank you ++!
