### ISSUE TITLE
Are these behaviors correct?

### ISSUE THREAD

**Issue by hiratara** [nexB/python-publicsuffix2#5]
I install this library and notice that it behaves differently from the spec.

For example, [spec](https://raw.githubusercontent.com/publicsuffix/list/master/tests/test_psl.txt) says,

> checkPublicSuffix('ac.jp', null);

But [your tests](https://github.com/nexB/python-publicsuffix2/blob/b7fae069079a79cdb9ad7525c1fb0005f131faf4/tests.py#L163) says:

> assert 'ac.jp' == psl.get_sld('ac.jp')

get_tld() returns more weird results.

```
>>> psl.get_tld("ac.jp")
'jp'
```

[PSL](https://publicsuffix.org/list/public_suffix_list.dat) has `ac.jp` entry, but publicsuffix2 returns `'jp'` . I tried other python libraries, but they all returns `ac.jp` .

```
>>> from publicsuffixlist import PublicSuffixList
>>> psl = PublicSuffixList()
>>> psl.publicsuffix("ac.jp")
'ac.jp'
```

```
>>> from dnspy.dnspy import Dnspy
>>> d = Dnspy()
>>> d.etld("ac.jp")
'ac.jp'
```

```
>>> import psl
>>> psl.domain_suffixes("ac.jp").public
'ac.jp'
```

**Comment by pombredanne** [comment]
@hiratara Thank you for this report and sorry for this bug.

**Comment by KnitCode** [comment]
@hiratara -- I think this is a language issue more than a performance issue; there *is* a documentation issue in the README. The publicsuffix2 library basic functionality returns the sld, or private suffix, relative to the domain. The libraries you compared with are returning the eTLD instead.  So the behavior you are seeing should only occur in the case that you have entered an eTLD as the domain.  That's pretty rare. Do you have a use case for it? That might help. 

Given the language clarification, the library is working as I'd expect in the DNS world. It returns the best answer, relative to the domain submitted. In the case you provided, 'ac.jp' -- it by itself is an eTLD.    
* psl.get_public_suffix('ac.jp') returns 'ac.jp'.  this matches the other libraries you listed. this is the public suffix ('ac.jp'). the get_sld('ac.jp') also returns 'ac.jp', as relative to  jp it is also the sld. 
* psl.get_tld('ac.jp') returns the tld for 'ac.jp', which is 'jp'.  The documentation says you will get the eTLD, but in fact, it's set to get the tld w/ respect to the domain provided. in this case, that is 'jp'. *this is an error in the documentation i will fix*.

How does this differ from your expectations given the clarification? 
Recommendations to make the README clearer are helpful.

**Comment by hiratara** [comment]
> Do you have a use case for it?

I try to verify the domain which is submitted from the web form, so it might be eTLD. I want to know what "the registrable domain" is for a submitted domain, or that a submitted domain is not registrable. `publicsuffixlist` 's `privatesuffix`works perfectly as I expected.

```
>>> from publicsuffixlist import PublicSuffixList
>>> psl = PublicSuffixList()
>>> psl.privatesuffix("www.example.co.uk")
'example.co.uk'
>>> psl.privatesuffix("example.co.uk")
'example.co.uk'
>>> psl.privatesuffix("co.uk")
>>> psl.privatesuffix("uk")
```

I read your examples and it listed the following results. So, I think `get_public_suffix` returns the registrable domain. ( However, it is strange that `get_public_suffix` returns **something that is not Public Suffix** )

```
>>> get_public_suffix('www.example.co.uk')
'example.co.uk'
>>> get_public_suffix('www.super.example.co.uk')
'example.co.uk'
```

> this is a language issue

I agree with you. I think about each term as follows. Is this correct?

* assume the input is `www.example.co.uk`
    * TLD: `uk`
    * SLD: `co.uk` (or just `co` )
    * eTLD, or public suffix: `co.uk`
    * the registrable domain, or private suffix: `example.co.uk`
* assume the input is `www.example.com`
    * TLD: `com`
    * SLD: `example.com` (or just `example`)
    * eTLD, or public suffix: `com`
    * the registrable domain, or private suffix: `example.com`
* assume the input is `co.uk`
    * TLD: `uk`
    * SLD: `co.uk` (or just `co`)
    * eTLD, or public suffix: `co.uk`
    * the registrable domain, or private suffix: None
* assume the input is `com`
    * TLD: `com`
    * SLD: None
    * eTLD, or public suffix: `com`
    * the registrable domain, or private suffix: None

Based on the above, I am confused about what `get_tld` and `get_sld` return.

```
>>> psl.get_sld("www.example.co.uk")
'example.co.uk'
>>> psl.get_tld("www.example.co.uk")
'co.uk'
>>> psl.get_sld("www.example.com")
'example.com'
>>> psl.get_tld("www.example.com")
'com'
>>> psl.get_sld("co.uk")
'co.uk'
>>> psl.get_tld("co.uk")
'uk'
>>> psl.get_sld("com")
'com'
>>> psl.get_tld("com")
'com'
```

**Comment by KnitCode** [comment]
@hiratara thanks. I understand your use case.  publicsuffixlist library has the privatesuffix (which to me is also a strange term ;) ) and that returns the sld, if it exists, and None if it does not.  in the publicsuffix2 library, the functions get_private_suffix / get_sld match the functionality of privatesuffix, except in the case that the domain queried is itself an eTLD. 

You are using the response of None to determine that it is not registrable. For other use cases (dns log processing, for example) a return of None is a problem for the downstream uses. 

if get_tld was modified to always return the eTLD itself, e.g.,  'ac.jp' returns 'ac.jp', you could make the decision you need, i believe, without adversely effecting other use cases, esp as this is only an edge case.

**Comment by pombredanne** [comment]
@KnitCode could it make sense to add a function for `get_etld()` ?

**Comment by hiratara** [comment]
> if get_tld was modified to always return the eTLD itself

It looks good to me 👍

One more thing, we had better document what happens when you pass eTLD to `get_public_suffix` . Document says:

> The module provides two equivalent functions to query a domain name, and return the base domain, or second-level-doamin; get_public_suffix() and get_sld():

However, I don't know what "ac.jp" and "com" 's base domains are.

**Comment by KnitCode** [comment]
the get_tld is a kludge right now. it can be redone, i expect, to use the Trie directly and get the eTLD. 

the base domain for 'com' is com. DNS is quite arcane, and there is a lot of mixed language. we can add to the documentation that in the event you pass an TLD/eTLD, the return value will be an TLD/eTLD.  note this is true even if the tld is not valid. 

unless the strict flag is set, there is no checking of the tld for validity.  for your use case, you'll probably want to set strict=True.  both publicsuffix2 and publicsuffixlist will tell you that the sld of 'blah.internal' is 'blah.internal' by default.

**Comment by hiratara** [comment]
> we can add to the documentation that in the event you pass an TLD/eTLD, the return value will be an TLD/eTLD.

It's a good idea 😄

> for your use case, you'll probably want to set strict=True.

I have noticed that flag. It seems to be useful for my use case.

**Comment by hiratara** [comment]
@pombredanne @KnitCode 

I created pull requests.

> if get_tld was modified to always return the eTLD itself

See #6. 

> we can add to the documentation that in the event you pass an TLD/eTLD, the return value will be an TLD/eTLD.

See #7.

**Comment by hiratara** [comment]
@pombredanne What do you think about #6 and #7? If I have other things to do, please let me know.

**Comment by pombredanne** [comment]
@hiratara let me review this today!
Sorry for the delay but there were some holidays in between.

**Comment by KnitCode** [comment]
i reviewed a few weeks ago. fixes look good to me. thanks for the help @hiratara ... i had some ask me about this exact issue today and i told them a fix was coming.

**Comment by pombredanne** [comment]
All set. Thank you again!
